## ============================
# GroupDNA - WhatsApp Analyzer
# Minor Project
##============================

**Libraries Used:** NumPy, datetime, re, collections

In [2]:
import re
import numpy as np
from datetime import datetime
from collections import Counter

In [1]:
from google.colab import files

uploaded = files.upload()

Saving hostel_bois.txt to hostel_bois.txt


In [3]:
with open("hostel_bois.txt", "r", encoding="utf-8") as file:
    chat_lines = file.readlines()

print("File Loaded Successfully")
print("Total Lines :", len(chat_lines))

File Loaded Successfully
Total Lines : 3178


In [4]:
pattern = r'^(\d{2}/\d{2}/\d{2}), (\d{2}:\d{2}) - (.*?): (.*)$'

messages = []

for line in chat_lines:

    line = line.strip()

    match = re.match(pattern, line)

    if match:

        date = match.group(1)
        time = match.group(2)
        sender = match.group(3)
        message = match.group(4)

        messages.append({
            "date": date,
            "time": time,
            "sender": sender,
            "message": message
        })

print("Messages Parsed :", len(messages))

Messages Parsed : 3174


In [5]:
participants = set()

message_count = Counter()

date_count = Counter()

hour_count = Counter()

for msg in messages:

    participants.add(msg["sender"])

    message_count[msg["sender"]] += 1

    date_count[msg["date"]] += 1

    hour = int(msg["time"].split(":")[0])

    hour_count[hour] += 1

print("Participants :", len(participants))

print("Total Messages :", len(messages))

Participants : 6
Total Messages : 3174


In [6]:
most_active = max(message_count, key=message_count.get)

most_active_day = max(date_count, key=date_count.get)

most_active_hour = max(hour_count, key=hour_count.get)

print("="*50)

print("GROUP OVERVIEW")

print("="*50)

print("Participants :", len(participants))

print("Messages :", len(messages))

print("Most Active Person :", most_active)

print("Most Active Day :", most_active_day)

print("Most Active Hour :", f"{most_active_hour}:00")

GROUP OVERVIEW
Participants : 6
Messages : 3174
Most Active Person : Rahul
Most Active Day : 04/05/24
Most Active Hour : 18:00


In [7]:
all_text = ""

for msg in messages:

    all_text += " " + msg["message"].lower()

clean_text = re.sub(r"[^a-zA-Z\s]", "", all_text)

words = clean_text.split()

stop_words = {
"the","is","am","are","was","were","a","an","and","or","to","of",
"in","on","for","with","at","by","from","as","it","its","this",
"that","be","been","being","i","me","my","we","our","you","your",
"he","she","they","them","their","him","her","do","does","did",
"have","has","had","will","would","can","could","should","shall",
"if","but","so","because","not","yes","no","ok","okay","ya","yeah",
"im","ill","dont","cant","bro","bhai","guys","lol","haha"
}

filtered_words = []

for word in words:

    if word not in stop_words and len(word) > 2:

        filtered_words.append(word)

word_count = Counter(filtered_words)

print("="*50)

print("TOP 10 WORDS")

print("="*50)

for word,count in word_count.most_common(10):

    print(word,"-",count)

TOP 10 WORDS
how - 321
about - 274
hai - 268
today - 257
his - 217
just - 208
which - 202
everyone - 187
telling - 179
one - 157


In [8]:
activity_matrix = np.zeros((24,7),dtype=int)

for msg in messages:

    date_obj = datetime.strptime(msg["date"],"%d/%m/%y")

    day = date_obj.weekday()

    hour = int(msg["time"].split(":")[0])

    activity_matrix[hour][day] += 1

print("Activity Matrix")

print(activity_matrix)

Activity Matrix
[[ 8 11  6  7  5 11  9]
 [17 16 11  5 11 15  7]
 [13 13 12 15 17  9  4]
 [11 25  6 14  4 10  7]
 [11 14 11  9 22 17 26]
 [ 0 12  4  6  3  0  4]
 [ 4  4  0  1  6  3 15]
 [10  9  8  9  4  7  8]
 [18 18 20 16 21 14 15]
 [12 21 31 23 26 21 17]
 [18 19 25 20 23 23 32]
 [15  7 15 30 11 14 22]
 [31 21 27 37 23 20 34]
 [30 18 17 24 25 22 23]
 [18 20 37 26 18 25 18]
 [20  8 27 18 22  9 27]
 [30 27 38 33 17 25 19]
 [23 26 25 19 17 40 23]
 [49 40 21 36 41 34 27]
 [35 16 34 35 25 43 40]
 [30 21 26 32 15 20 22]
 [32 29 46 18 18 17 17]
 [19 15 19 20 12 15 16]
 [28 16 17 22 17 45 14]]


In [9]:
spammer = max(message_count,key=message_count.get)

ghost = min(message_count,key=message_count.get)

night_count = Counter()

for msg in messages:

    hour = int(msg["time"].split(":")[0])

    if hour >=23 or hour<5:

        night_count[msg["sender"]]+=1

night_owl = max(night_count,key=night_count.get) if night_count else "None"

print("="*60)

print("GROUP DNA REPORT")

print("="*60)

print("Total Messages :",len(messages))

print("Participants :",len(participants))

print("Most Active :",most_active)

print("Spammer :",spammer)

print("Ghost :",ghost)

print("Night Owl :",night_owl)

print("Most Active Day :",most_active_day)

print("Most Active Hour :",f"{most_active_hour}:00")

print("Top Word :",word_count.most_common(1)[0][0])

print("="*60)

GROUP DNA REPORT
Total Messages : 3174
Participants : 6
Most Active : Rahul
Spammer : Rahul
Ghost : Vikas
Night Owl : Aman
Most Active Day : 04/05/24
Most Active Hour : 18:00
Top Word : how


In [10]:
print("=" * 60)
print("MESSAGE SHARE")
print("=" * 60)

total = len(messages)

for person, count in message_count.most_common():

    percentage = (count / total) * 100

    print(f"{person:<15} {count:>4} messages   ({percentage:.2f}%)")

MESSAGE SHARE
Rahul            953 messages   (30.03%)
Priya            718 messages   (22.62%)
Neha             635 messages   (20.01%)
Aman             490 messages   (15.44%)
Karan            354 messages   (11.15%)
Vikas             24 messages   (0.76%)


In [11]:
print("=" * 60)
print("TOP 5 ACTIVE MEMBERS")
print("=" * 60)

rank = 1

for person, count in message_count.most_common(5):

    bar = "█" * (count // 5)

    print(f"{rank}. {person}")
    print(f"   Messages : {count}")
    print(f"   {bar}")
    print()

    rank += 1

TOP 5 ACTIVE MEMBERS
1. Rahul
   Messages : 953
   ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

2. Priya
   Messages : 718
   ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

3. Neha
   Messages : 635
   ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

4. Aman
   Messages : 490
   ██████████████████████████████████████████████████████████████████████████████████████████████████

5. Karan
   Messages : 354
   ██████████████████████████████████████████████████████████████████████



In [12]:
report = f"""
=============================
GROUP DNA REPORT
=============================

Total Messages : {len(messages)}

Participants : {len(participants)}

Most Active : {most_active}

Spammer : {spammer}

Ghost : {ghost}

Night Owl : {night_owl}

Most Active Day : {most_active_day}

Most Active Hour : {most_active_hour}:00

Top Word : {word_count.most_common(1)[0][0]}

=============================
"""

with open("Group_Report.txt", "w") as file:

    file.write(report)

print("Report Saved Successfully!")

Report Saved Successfully!


In [18]:
print("=" * 35)
print("GROUP DNA - WHATSAPP CHAT ANALYZER")
print("=" * 35)

print()

print("Project Completed Successfully!")

print()

print("Features Implemented")

print()

print(">> File Reading")

print(">> Chat Parsing")

print(">> Participant Detection")

print(">> Message Statistics")

print(">> Word Frequency Analysis")

print(">> Activity Heatmap using NumPy")

print(">> Most Active Person")

print(">> Most Active Day")

print(">> Most Active Hour")

print(">> Spammer Detection")

print(">> Ghost Detection")

print(">> Night Owl Detection")

print(">> Message Share Analysis")

print(">> Leaderboard")

print(">> Report Generation")

print()



GROUP DNA - WHATSAPP CHAT ANALYZER

Project Completed Successfully!

Features Implemented

>> File Reading
>> Chat Parsing
>> Participant Detection
>> Message Statistics
>> Word Frequency Analysis
>> Activity Heatmap using NumPy
>> Most Active Person
>> Most Active Day
>> Most Active Hour
>> Spammer Detection
>> Ghost Detection
>> Night Owl Detection
>> Message Share Analysis
>> Leaderboard
>> Report Generation

